version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/refashion-api/

permissions:
  - object: /home/ec2-user/refashion-api/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
