version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/refashion-api/
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/refashion-api/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 180

  AfterInstall:
    - location: scripts/install.sh
      timeout: 180

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
